### ISSUE TITLE
Fails to build on Ubuntu 11.10

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dxskj/firmware-mod-kit#40]
```
What steps will reproduce the problem?
1. Attempt to build firmware-mod-kit on xubuntu 11.10


What is the expected output? What do you see instead?
/home/james/Desktop/RE_p6250/firmware-mod-kit-read-only/trunk/src/others/squashf
s-3.2-r2-lzma//C/Compress/Lzma/libunlzma.a(uncomp.o): In function `sqlzma_un':
uncomp.c:(.text+0x66): undefined reference to `inflateReset'
uncomp.c:(.text+0xa7): undefined reference to `inflate'
uncomp.c:(.text+0x253): undefined reference to `zError'
/home/james/Desktop/RE_p6250/firmware-mod-kit-read-only/trunk/src/others/squashf
s-3.2-r2-lzma//C/Compress/Lzma/libunlzma.a(uncomp.o): In function `sqlzma_init':
uncomp.c:(.text+0x430): undefined reference to `inflateInit_'
collect2: ld returned 1 exit status
make[3]: *** [unsquashfs] Error 1
make[3]: Leaving directory 
`/home/james/Desktop/RE_p6250/firmware-mod-kit-read-only/trunk/src/others/squash
fs-3.2-r2-lzma/squashfs3.2-r2/squashfs-tools'
make[2]: *** [all] Error 2
make[2]: Leaving directory 
`/home/james/Desktop/RE_p6250/firmware-mod-kit-read-only/trunk/src/others/squash
fs-3.2-r2-lzma'
make[1]: *** [all] Error 2
make[1]: Leaving directory 
`/home/james/Desktop/RE_p6250/firmware-mod-kit-read-only/trunk/src/others'
make: *** [all] Error 2

This is the second error, the first one was fixed by switching out cramfsswap 
with a version referenced by: 
https://bugs.launchpad.net/ubuntu/+source/cramfsswap/+bug/770935

And I have no idea how to fix this one. 

What version of the product are you using? On what operating system?
SVN checkout from November 1, 2011

Please provide any additional information below.

I successfully built it on Ubuntu 10.04 without problem. 


```

Original issue reported on code.google.com by `Sunrunne...@gmail.com` on 2 Nov 2011 at 1:45

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
Original comment by `jeremy.collake@gmail.com` on 2 Nov 2011 at 1:50
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
Not unless zlib1g-dev installs differently than on 10.04.

james@james-virtual-machine:~/Desktop/RE_p6250/firmware-mod-kit-read-only/trunk/
src$ dpkg --get-selections | grep zlib
zlib1g                      install
zlib1g-dbg                  install
zlib1g-dev                  install


PS: Searched before posting, found: 
http://code.google.com/p/firmware-mod-kit/issues/detail?id=32 Followed 
solutions offered, and it didn't help. 
```

Original comment by `Sunrunne...@gmail.com` on 2 Nov 2011 at 2:01

**Comment by GoogleCodeExporter** [comment]
```
Maybe try reinstalling them. You are missing a dependency, or have something 
wrong. It does build under Ubuntu 11.10 fine.
```

Original comment by `jeremy.collake@gmail.com` on 2 Nov 2011 at 2:06

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
Original comment by `jeremy.collake@gmail.com` on 2 Nov 2011 at 2:16
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Tried again this morning with a fresh install of xubuntu 11.10, with the same 
result. I recorded it, if that helps: 
https://www.youtube.com/watch?v=sLcc8FiQzdg&hd=1&t=10m15s (only about a minuet 
of relevant info)

It boils down to: 
*install*
*install updates*
apt-get install build-essentials zlib1g-dev subversion
svn checkout http://firmware-mod-kit.googlecode.com/svn/trunk/ 
firmware-mod-kit-read-only
cd firmware-mod-kit-read-only/trunk/src
make

*error*
```

Original comment by `Sunrunne...@gmail.com` on 2 Nov 2011 at 3:05

**Comment by GoogleCodeExporter** [comment]
```
Yes, I apologize for being dismissive at first, we had gotten several easily 
dismissed cases like this. Anyway, I have to find time to test and look into 
this. Or Craig, if he gets the time. Please hold, and thanks ;)
```

Original comment by `jeremy.collake@gmail.com` on 2 Nov 2011 at 3:09

**Comment by GoogleCodeExporter** [comment]
```
It's fine, I'm still half expecting that I've made a mistake somewhere myself.
I'll see if I can find the issue, but  I probally lack the skillset.
```

Original comment by `Sunrunne...@gmail.com` on 2 Nov 2011 at 3:45

**Comment by GoogleCodeExporter** [comment]
```
At present on Ubuntu 11.10 I get a different error building cramfs. I have not 
looked into it much yet, but crc32 may have been removed from a shared library 
or CRT update. This could cause other build errors, though this is the first 
one I saw.

cramfsswap.c: In function ‘main’:
cramfsswap.c:112:8: warning: ignoring return value of ‘write’, declared 
with attribute warn_unused_result [-Wunused-result]
cramfsswap.c:242:10: warning: ignoring return value of ‘write’, declared 
with attribute warn_unused_result [-Wunused-result]
cramfsswap.c:250:10: warning: ignoring return value of ‘write’, declared 
with attribute warn_unused_result [-Wunused-result]
cramfsswap.c:302:12: warning: ignoring return value of ‘write’, declared 
with attribute warn_unused_result [-Wunused-result]
cramfsswap.c:328:12: warning: ignoring return value of ‘write’, declared 
with attribute warn_unused_result [-Wunused-result]
cramfsswap.c:341:10: warning: ignoring return value of ‘write’, declared 
with attribute warn_unused_result [-Wunused-result]
/tmp/ccMos4p2.o: In function `main':
/home/jeremy/firmware-mod-kit/trunk/src/cramfsswap/cramfsswap.c:348: undefined 
reference to `crc32'
/home/jeremy/firmware-mod-kit/trunk/src/cramfsswap/cramfsswap.c:350: undefined 
reference to `crc32'
/home/jeremy/firmware-mod-kit/trunk/src/cramfsswap/cramfsswap.c:350: undefined 
reference to `crc32'
collect2: ld returned 1 exit status
make[1]: *** [cramfsswap] Error 1
make[1]: Leaving directory `/home/jeremy/firmware-mod-kit/trunk/src/cramfsswap'
make: *** [all] Error 2

```

Original comment by `jeremy.collake@gmail.com` on 3 Nov 2011 at 4:12

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
The cramfsswap issue is a problem with the makefile. The -lz option should be 
at the end of the gcc line; moving it to the end of the gcc line fixes the 
build. I suspect the other squashfs issues are similar as some link against 
zlib fine while others fail. Should be an easy fix.
```

Original comment by `heffne...@gmail.com` on 4 Nov 2011 at 2:15

**Comment by GoogleCodeExporter** [comment]
```
Ah, good. Easy fix. I love it when programmers get more anal about command line 
ordering in later versions, something I've seen nowhere else outside linux ;p
```

Original comment by `jeremy.collake@gmail.com` on 4 Nov 2011 at 2:22

**Comment by GoogleCodeExporter** [comment]
```
Makefiles updated, builds properly on Ubunu 11.10.
```

Original comment by `heffne...@gmail.com` on 4 Nov 2011 at 3:10
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
```
As always, I, and all who use the FMK thank you Craig. For those who don't 
know, Craig has been the one who has revived, and indeed rewritten this project.
```

Original comment by `jeremy.collake@gmail.com` on 4 Nov 2011 at 4:14

**Comment by GoogleCodeExporter** [comment]
```
Thanks Jeremy, glad to help as always. :)
```

Original comment by `heffne...@gmail.com` on 4 Nov 2011 at 4:25

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
I have the same issue. I ran ./configure, then edited the Makefile in 
squashfs-tools and deleted -lz from line 13 (LD_LIBS += ...) and added it to 
the end of lines 26 and 32 (also LDLIBS += ... but as dependencies). That 
seemed to fix the problem.
```

Original comment by `ellieno...@gmail.com` on 10 Mar 2012 at 7:56

**Comment by GoogleCodeExporter** [comment]
```
[deleted comment]
```

**Comment by GoogleCodeExporter** [comment]
```
Actually two new squashfs variants were added. I've fixed them both now. 
Committing in minutes, making last tests.
```

Original comment by `jeremy.collake@gmail.com` on 10 Mar 2012 at 8:23

**Comment by GoogleCodeExporter** [comment]
```
Ok, give 'er a go now.
```

Original comment by `jeremy.collake@gmail.com` on 10 Mar 2012 at 8:29
